// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// credsetmat
List credsetmat(NumericMatrix pp, NumericVector iCV, double threshold);
RcppExport SEXP _corrcoverage_credsetmat(SEXP ppSEXP, SEXP iCVSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type iCV(iCVSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(credsetmat(pp, iCV, threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_corrcoverage_credsetmat", (DL_FUNC) &_corrcoverage_credsetmat, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_corrcoverage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
