# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator token:
# 10BE3573-1514-4C36-9D1C-5A225CD40393

credsetmat <- function(pp, iCV, threshold) {
    .Call("_corrcoverage_credsetmat", PACKAGE = "corrcoverage", pp, iCV, threshold)
}

colsort <- function(tpp) {
    .Call("_corrcoverage_colsort", PACKAGE = "corrcoverage", tpp)
}

colcumsum <- function(x) {
    .Call("_corrcoverage_colcumsum", PACKAGE = "corrcoverage", x)
}

colrank <- function(x, pp) {
    .Call("_corrcoverage_colrank", PACKAGE = "corrcoverage", x, pp)
}

blockcolrank <- function(x, pp, blocksize) {
    .Call("_corrcoverage_blockcolrank", PACKAGE = "corrcoverage", x, pp, blocksize)
}

blockcoldist <- function(x, pp, blocksize) {
    .Call("_corrcoverage_blockcoldist", PACKAGE = "corrcoverage", x, pp, blocksize)
}

